<a href="https://colab.research.google.com/github/parkash-arjan/machine-learning/blob/master/eigen_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def plot_vector(vectors , columns , alpha=1):
  plt.figure()
  plt.axvline(x=0, color='#A9A9A9' , zorder=0)
  plt.axhline(y=0, color='#A9A9A9' , zorder=0)
  for i in range(len(vectors)):
    x=np.concatenate([[0,0],vectors[i]])
    plt.quiver(x[0],
               x[1],
               x[2],
               x[3],
               angles = 'xy' , scale_units='xy',scale=1,color=columns[i],alpha=alpha)
    plt.grid(True)  

In [3]:
M = np.array([[1,2,1],[0,1,1],[1,0,1]])
print(M)

[[1 2 1]
 [0 1 1]
 [1 0 1]]


In [11]:
Lambda,U  = np.linalg.eig(M) 

In [12]:
print(U)

[[ 0.78598962+0.j          0.65381281+0.j          0.65381281-0.j        ]
 [ 0.33957958+0.j         -0.0595103 +0.49377558j -0.0595103 -0.49377558j]
 [ 0.51662949+0.j         -0.37832817-0.4266624j  -0.37832817+0.4266624j ]]


In [13]:
print(Lambda)

[2.52137971+0.j         0.23931015+0.85787363j 0.23931015-0.85787363j]


In [15]:
inv_U = np.linalg.inv(U)
print(inv_U)

[[ 0.49544457-7.06258072e-17j  0.65130955+0.00000000e+00j
   0.75375931+1.05938711e-16j]
 [ 0.4669423 +1.14087359e-01j -0.39149014-7.41463535e-01j
  -0.4530708 +3.13792385e-01j]
 [ 0.4669423 -1.14087359e-01j -0.39149014+7.41463535e-01j
  -0.4530708 -3.13792385e-01j]]


In [16]:
dig = np.diag(Lambda)
print(dig) 

[[2.52137971+0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.23931015+0.85787363j 0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.23931015-0.85787363j]]


In [17]:
def round(values,decs=0):
  return np.round(values*10**decs)/(10**decs)

In [21]:
vec = np.dot(U , np.dot(dig,inv_U)) 
round(vec,decs=0)

array([[1.-0.j, 2.+0.j, 1.+0.j],
       [0.-0.j, 1.-0.j, 1.+0.j],
       [1.+0.j, 0.-0.j, 1.+0.j]])

In [22]:
print(M)

[[1 2 1]
 [0 1 1]
 [1 0 1]]
